platform :ios, '15.0'

# CocoaPods analytics sends network stats synchronously affecting build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def dn_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'DartNative', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"dn pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/DN_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "DN_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run \"dn pub get\""
end

require File.expand_path(File.join('bin', 'podhelper'), dn_root)

dartnative_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  dartnative_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    dartnative_additional_ios_build_settings(target)
    target.build_configurations.each { |config| config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0' }
  end
end
